# Generated by Django 4.2.11 on 2024-07-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_post_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_duration',
            field=models.IntegerField(default=0),
        ),
    ]
