# Generated by Django 4.2.11 on 2024-07-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_post_video_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('singer', 'Singer'), ('dj', 'DJ'), ('other', 'Other')], default='other', max_length=10),
        ),
    ]
