# Generated by Django 4.2.11 on 2024-08-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_userpostcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='unkown', max_length=100),
        ),
    ]
