# Generated by Django 4.2.11 on 2024-09-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_product_remove_userpostcount_user_delete_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AlterField(
            model_name='product',
            name='bar_code',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
