# Generated by Django 4.2.11 on 2024-09-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_product_bar_code_remove_product_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('IN', 'In Stock'), ('OUT', 'Out of Stock')], default='IN', max_length=10),
        ),
    ]
