# Generated by Django 4.2.11 on 2024-10-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_product_last_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cost_of_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('operating_expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('other_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('other_expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
