# Generated by Django 4.2.11 on 2024-10-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_incomestatement_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomestatement',
            name='operating_expenses',
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='dividends',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='insurance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='interest',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='marketing',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='rent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='salaries',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='utilities',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
