# Generated by Django 4.2.11 on 2024-12-20 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_barcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Barcode',
        ),
        migrations.RemoveField(
            model_name='incomestatement',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='product',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='IncomeStatement',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='SaleItem',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
