# Generated by Django 4.2.11 on 2025-01-02 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submit', '0047_alter_passwordresetrequest_token_delete_booking'),
        ('core', '0034_delete_barcode_remove_incomestatement_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=50)),
                ('capacity', models.IntegerField(default=5)),
                ('booked_count', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('date', 'time')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.timeslot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submit.customuser')),
            ],
            options={
                'unique_together': {('user', 'time_slot')},
            },
        ),
    ]
