# Generated by Django 4.2.11 on 2025-01-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='reference',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('collected', 'Collected'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
