# Generated by Django 4.2.11 on 2025-01-06 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_booking_collected_at_booking_reference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('house_number', models.CharField(max_length=20)),
                ('street_name', models.CharField(max_length=100)),
                ('place_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
        migrations.AddField(
            model_name='paymentstatus',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.resident'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentstatus',
            unique_together={('resident', 'month')},
        ),
    ]
