# Generated by Django 4.2.11 on 2025-01-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_dailyverse_question_userresponse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('book', models.CharField(max_length=50)),
                ('chapter', models.IntegerField()),
                ('start_verse', models.IntegerField()),
                ('original_text', models.TextField()),
                ('simplified_text', models.TextField()),
                ('study_questions', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='daily_verse',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='question',
        ),
        migrations.DeleteModel(
            name='DailyVerse',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='UserResponse',
        ),
    ]
