# Generated by Django 4.2.11 on 2025-02-16 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0059_alter_passwordresetrequest_token'),
        ('core', '0041_dailyquestions_userresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reflection',
            name='likes',
            field=models.ManyToManyField(related_name='liked_reflections', to='submit.customuser'),
        ),
        migrations.AlterField(
            model_name='reflection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submit.customuser'),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submit.customuser'),
        ),
    ]
