# Generated by Django 4.2.11 on 2025-02-17 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_userresponse_points_earned_userstats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='points_earned',
        ),
        migrations.DeleteModel(
            name='UserStats',
        ),
    ]
