# Generated by Django 4.2.11 on 2025-02-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_gratitudeentry_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('NS', 'Not Started'), ('IP', 'In Progress'), ('CM', 'Completed')], default='IP', max_length=2),
        ),
    ]
