# Generated by Django 4.2.11 on 2025-02-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_alter_category_options_remove_song_artist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('NC', 'Not Completed'), ('IP', 'In Progress'), ('CM', 'Completed')], default='IP', max_length=2),
        ),
    ]
