# Generated by Django 4.2.11 on 2025-03-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_savedreflection'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album_art',
            field=models.FileField(blank=True, null=True, upload_to='albumart/'),
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
