# Generated by Django 4.2.11 on 2025-04-08 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_song_album_art_song_artist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyPrayer',
        ),
        migrations.DeleteModel(
            name='DailyQuestions',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='user',
        ),
        migrations.RemoveField(
            model_name='gratitudeentry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='question',
            name='passage',
        ),
        migrations.RemoveField(
            model_name='reflection',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='reflection',
            name='question',
        ),
        migrations.RemoveField(
            model_name='reflection',
            name='user',
        ),
        migrations.RemoveField(
            model_name='rosaryprogress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='savedreflection',
            name='reflection',
        ),
        migrations.RemoveField(
            model_name='savedreflection',
            name='user',
        ),
        migrations.RemoveField(
            model_name='song',
            name='category',
        ),
        migrations.DeleteModel(
            name='TraditionalPrayer',
        ),
        migrations.AlterUniqueTogether(
            name='userresponse',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='DailyPassage',
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
        migrations.DeleteModel(
            name='GratitudeEntry',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Reflection',
        ),
        migrations.DeleteModel(
            name='RosaryProgress',
        ),
        migrations.DeleteModel(
            name='SavedReflection',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
        migrations.DeleteModel(
            name='UserResponse',
        ),
    ]
