# Generated by Django 5.1.6 on 2025-05-06 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_initial'),
        ('submit', '0079_rename_account_name_customuser_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submit.customuser'),
        ),
    ]
