# Generated by Django 5.0.3 on 2024-06-08 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='birth',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='food',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='name',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='phone',
        ),
    ]
