# Generated by Django 4.2.11 on 2024-07-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0003_profile_delete_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='category',
            field=models.CharField(choices=[('singer', 'Singer'), ('dj', 'DJ'), ('other', 'Other')], default='other', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
