# Generated by Django 4.2.11 on 2024-08-07 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0006_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
