# Generated by Django 5.0.3 on 2024-08-19 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0009_profile_total_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='total_posts',
        ),
    ]
