# Generated by Django 4.2.11 on 2024-11-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0014_alter_customuser_managers_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='Nk3kLWHeq3UGsgPb9sr1NXg0TIScGWG3', editable=False, max_length=32, unique=True),
        ),
    ]
