# Generated by Django 5.0.3 on 2024-11-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0015_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='X29W5QCYuRWaquy8Jg2Za7TZQKr4FJsY', editable=False, max_length=32, unique=True),
        ),
    ]
