# Generated by Django 5.0.3 on 2024-11-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0018_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='6uN12GhL7xnLkcV2Nl66LeAeLlEWr6Ky', editable=False, max_length=32, unique=True),
        ),
    ]
