# Generated by Django 5.0.3 on 2024-11-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0020_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='J9M7vQIX4KdQinTBKaOJjbyj0T5xc2ZL', editable=False, max_length=32, unique=True),
        ),
    ]
