# Generated by Django 4.2.11 on 2024-11-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0021_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='0dL82LdwkQqT1RcKOSOFNlPTe3T1txGd', editable=False, max_length=32, unique=True),
        ),
    ]
