# Generated by Django 4.2.11 on 2024-11-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0022_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='BlQ4dfcW0A6myt93qjDQ3dYqAuYAicA9', editable=False, max_length=32, unique=True),
        ),
    ]
