# Generated by Django 5.0.3 on 2024-11-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0027_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='l8c2l3kF4Cd4c4CnGtTuUXgN2pNwPu8Z', editable=False, max_length=32, unique=True),
        ),
    ]
