# Generated by Django 5.0.3 on 2024-11-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0030_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='8gdfAXsKQWYQumkYdCP2z7p2f8kuEP8q', editable=False, max_length=32, unique=True),
        ),
    ]
