# Generated by Django 4.2.11 on 2024-11-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0031_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='Og6tyBT0p4NtwN3XVAoic5iG3UEv1E7f', editable=False, max_length=32, unique=True),
        ),
    ]
