# Generated by Django 4.2.11 on 2024-12-06 09:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0032_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='4t8pIUOeZlW0c0przZUH2CKQretxsaMl', editable=False, max_length=32, unique=True),
        ),
    ]
