# Generated by Django 4.2.11 on 2024-12-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0034_subscriptionplan_alter_passwordresetrequest_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='admin_password',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='LWUpjbg4tI4JsEhywg4jwOzDJk4AaCIl', editable=False, max_length=32, unique=True),
        ),
    ]
