# Generated by Django 4.2.11 on 2024-12-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0036_alter_passwordresetrequest_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpasswordresetrequest',
            name='token',
            field=models.CharField(default='nu2oqXoUFCW4ho0VlceK6kutEAnrKgBs', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='ULz12eLBplCEEbCoKc2qZ2bkbfrboP9J', editable=False, max_length=32, unique=True),
        ),
    ]
