# Generated by Django 4.2.11 on 2024-12-20 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('submit', '0037_alter_adminpasswordresetrequest_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.IntegerField(choices=[(8, '8:00 AM'), (9, '9:00 AM'), (10, '10:00 AM'), (11, '11:00 AM'), (12, '12:00 PM'), (13, '1:00 PM'), (14, '2:00 PM'), (15, '3:00 PM'), (16, '4:00 PM'), (17, '5:00 PM')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='company_name',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='admin_password',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pricing_plan',
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='qoWCSTunOB0aOXC6sKEtdLY8SfKYeBBl', editable=False, max_length=32, unique=True),
        ),
        migrations.DeleteModel(
            name='AdminPasswordResetRequest',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['date', 'hour'], name='submit_book_date_f46fea_idx'),
        ),
    ]
