# Generated by Django 4.2.11 on 2024-12-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0038_booking_remove_service_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='CA3BWdaNq6do1PwAkOSn246MSjGHjhFO', editable=False, max_length=32, unique=True),
        ),
    ]
