# Generated by Django 4.2.11 on 2024-12-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0039_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='1YLdd5YeSOlneLZ5iDXPpSORjHl7V0b5', editable=False, max_length=32, unique=True),
        ),
    ]
