# Generated by Django 4.2.11 on 2024-12-20 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0042_remove_booking_submit_book_date_f46fea_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submit.customuser'),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='udauxl1tpXFST4BS7CQmPtkKzT59scGq', editable=False, max_length=32, unique=True),
        ),
    ]
