# Generated by Django 4.2.11 on 2024-12-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0043_alter_booking_user_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='BHp5EtAnek0K14lKz1nY2Q9B7wCwbOi8', editable=False, max_length=32, unique=True),
        ),
    ]
