# Generated by Django 4.2.11 on 2024-12-20 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0044_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='submit.customuser'),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='L2igWbbNwT96H7ltBCyTMAHE3RvoFM11', editable=False, max_length=32, unique=True),
        ),
    ]
