# Generated by Django 4.2.11 on 2024-12-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0045_alter_booking_user_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='QKXNyhIamUmIklA3c6ePxbCGxpOKv2xu', editable=False, max_length=32, unique=True),
        ),
    ]
