# Generated by Django 4.2.11 on 2025-01-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0046_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='iM0PjMHkfWtU1FCFaBY7VBFJdTrI3flC', editable=False, max_length=32, unique=True),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
