# Generated by Django 4.2.11 on 2025-01-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0047_alter_passwordresetrequest_token_delete_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='7wldfjKzU0eVjvSdzj9B4zpgzU4OkP3m', editable=False, max_length=32, unique=True),
        ),
    ]
