# Generated by Django 4.2.11 on 2025-01-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0048_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='CgSZhex0ehjQpGcqoAqGMHzvIfOYEO9R', editable=False, max_length=32, unique=True),
        ),
    ]
