# Generated by Django 4.2.11 on 2025-01-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0049_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='x4C8xvMiXVaceedEazW6Br4mmq59qfW8', editable=False, max_length=32, unique=True),
        ),
    ]
