# Generated by Django 4.2.11 on 2025-01-06 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0052_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='6hap0973tWwwrIWZvYcQK0roL6g9VPFK', editable=False, max_length=32, unique=True),
        ),
    ]
