# Generated by Django 4.2.11 on 2025-01-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0053_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='GAl3ArorGqKQQriBoOOIgADWzUAqSUj2', editable=False, max_length=32, unique=True),
        ),
    ]
