# Generated by Django 4.2.11 on 2025-01-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0054_remove_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='3OcrcBypc7b96M9QeJvFpRBrKi6bvzZY', editable=False, max_length=32, unique=True),
        ),
    ]
