# Generated by Django 4.2.11 on 2025-01-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0055_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='ylOMPcm7LGTNcF37mLnwJWHW5OLnYk2r', editable=False, max_length=32, unique=True),
        ),
    ]
