# Generated by Django 4.2.11 on 2025-01-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0056_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='feddV5bIBEGPDtfoU0VlyFIE1u3PqCVm', editable=False, max_length=32, unique=True),
        ),
    ]
