# Generated by Django 4.2.11 on 2025-02-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0057_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='OId5slCzYv4hO9zG8NydMGIYfjAdR9Mp', editable=False, max_length=32, unique=True),
        ),
    ]
