# Generated by Django 4.2.11 on 2025-02-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0058_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='9IEvMth4Vz7GF2RPYsElm2PqfsDLEem2', editable=False, max_length=32, unique=True),
        ),
    ]
