# Generated by Django 4.2.11 on 2025-02-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0060_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='zPqpB2klp6oUtnoSW33ieOayyWN1N19c', editable=False, max_length=32, unique=True),
        ),
    ]
