# Generated by Django 4.2.11 on 2025-02-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0061_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='3sKESsllRFrRhwqgBLZYTjrP9byXnbld', editable=False, max_length=32, unique=True),
        ),
    ]
