# Generated by Django 4.2.11 on 2025-02-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0062_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='ocQKU54OAJoGt23lB3KXTkrpzSzSCgie', editable=False, max_length=32, unique=True),
        ),
    ]
