# Generated by Django 4.2.11 on 2025-02-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0063_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='c9chszRoO80j9yC69QCPba8W1Iqgfcs2', editable=False, max_length=32, unique=True),
        ),
    ]
