# Generated by Django 4.2.11 on 2025-02-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0065_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='boPPRr1XpCbnOOBsqivou2pw7ujbcjnc', editable=False, max_length=32, unique=True),
        ),
    ]
