# Generated by Django 4.2.11 on 2025-02-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0066_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='NpojwM9Y7X1YZOQrvWHmgs56LCRivF2M', editable=False, max_length=32, unique=True),
        ),
    ]
