# Generated by Django 4.2.11 on 2025-02-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0067_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='zizTjViLFnI7piv4Gl9oUkJ8QGW1Ty9g', editable=False, max_length=32, unique=True),
        ),
    ]
