# Generated by Django 4.2.11 on 2025-02-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0068_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='JAiOhEhLcGsUcXt11lP11MluRfX84Haf', editable=False, max_length=32, unique=True),
        ),
    ]
