# Generated by Django 4.2.11 on 2025-03-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0069_customuser_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, choices=[('US', 'United States'), ('CA', 'Canada'), ('GB', 'United Kingdom'), ('AU', 'Australia'), ('FR', 'France'), ('DE', 'Germany'), ('IN', 'India'), ('JP', 'Japan'), ('CN', 'China'), ('BR', 'Brazil'), ('IT', 'Italy'), ('ES', 'Spain'), ('NL', 'Netherlands'), ('SE', 'Sweden'), ('NO', 'Norway'), ('ZA', 'South Africa'), ('NG', 'Nigeria'), ('KE', 'Kenya'), ('EG', 'Egypt'), ('GH', 'Ghana')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='6RJQ6hXlau1OEbvcQ2oGmAV5UATTLLOp', editable=False, max_length=32, unique=True),
        ),
    ]
