# Generated by Django 4.2.11 on 2025-03-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0070_customuser_city_customuser_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='color1',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='color2',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='initials',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='i9KrfxSGQta3xhgwQypVEYvgaimxTLf9', editable=False, max_length=32, unique=True),
        ),
    ]
