# Generated by Django 4.2.11 on 2025-03-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0071_customuser_color1_customuser_color2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='J8ClmxQ074NtTiAn0FlrfwiyGwo5f4Xn', editable=False, max_length=32, unique=True),
        ),
    ]
