# Generated by Django 4.2.11 on 2025-03-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0072_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='YinGQHpZIGOJ2lGc32gu9S3SCi2w4LTX', editable=False, max_length=32, unique=True),
        ),
    ]
