# Generated by Django 4.2.11 on 2025-03-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0073_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='hGyCdV7FeoR7x4d6wkqGUo1jBGQWbnnE', editable=False, max_length=32, unique=True),
        ),
    ]
