# Generated by Django 4.2.11 on 2025-04-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0075_remove_customuser_city_remove_customuser_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='8GuvnK5ANYC3GKE9jcNtB0H0884x0aMo', editable=False, max_length=32, unique=True),
        ),
    ]
