# Generated by Django 5.1.6 on 2025-04-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0077_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='zKgYz23DsXl0Fd4WO7KwEhZRFjYhas8v', editable=False, max_length=32, unique=True),
        ),
    ]
