# Generated by Django 5.1.6 on 2025-05-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0078_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='account_name',
            new_name='company_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='color1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='color2',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='initials',
        ),
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, choices=[('US', 'United States'), ('CA', 'Canada'), ('GB', 'United Kingdom'), ('AU', 'Australia'), ('FR', 'France'), ('DE', 'Germany'), ('IN', 'India'), ('JP', 'Japan'), ('CN', 'China'), ('BR', 'Brazil'), ('IT', 'Italy'), ('ES', 'Spain'), ('NL', 'Netherlands'), ('SE', 'Sweden'), ('NO', 'Norway'), ('ZA', 'South Africa'), ('NG', 'Nigeria'), ('KE', 'Kenya'), ('EG', 'Egypt'), ('GH', 'Ghana')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('customs Agent', 'Customs Agent')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='SyVcAz2qfPcq8beFz0bPuihkeCp83XSJ', editable=False, max_length=32, unique=True),
        ),
    ]
